### PR TITLE
update bug report link to github issues page

### LINKED ISSUE #27: support.html bug report link
support.html directs you to https://rt.cpan.org/Public/Dist/Display.html?Name=Perl-Dist-Strawberry for making bug reports.  But that page says that https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues is the preferred bug tracker.

image

If github issues are preferred, then support.html should direct the user straight to the preferred site.  If rt.cpan.org is preferred, then the message there should be removed.  If you don't actually care which tracker is used, then maybe support.html should link to both.

### LINKED ISSUE #91: https://strawberryperl.com/support.html still links to rt.cpan.org, which doesn't seem to want to be linked to
# What I saw:

Quoth https://strawberryperl.com/support.html

> Bug Reports
>
> please file a bug report (with as much details as possible) on our [Request Tracker](https://rt.cpan.org/Public/Dist/Display.html?Name=Perl-Dist-Strawberry)

but when you click the RT link, it says: 

Screen Shot 2023-04-13 at 12 31 41

... which links here. 

# What I expected:

The "Bug Reports" section to link to the bug reporting site.

# Steps to reproduce

1. https://strawberryperl.com/support.html
2. scroll down a bit
3. click `Request Tracker`

# Suggested fix

1. update the link on the website, or  
2. jam a bug reporting form directly into the page, or 
4. ask rt.cpan.org to redirect instead of showing a list of tickets it knows nobody is looking at

### PR DESCRIPTION
**Pull request by pryrt**
changes link from https://rt.cpan.org/Public/Dist/Display.html?Name=Perl-Dist-Strawberry to https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/ as the preferred bug tracker

closes #27
closes https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/91

### CODE REVIEW

**Comment by guest20** [comment]
This is a great idea!

**Comment by shawnlaffan** [comment]
@genio - this looks good to me.

**Comment by genio** [comment]
Looks good to me. Thank you! I'll leave it open until we have the credentials to publish to the site.

**Comment by shawnlaffan** [comment]
@genio - Have you been able to obtain the site credentials?

**Comment by genio** [comment]
Matt is working on it. He has my public SSH key. They're working on getting the billing right and ensuring things are good for the future. Should be all good to go in a few days or so

**Comment by shawnlaffan** [comment]
Thanks.  That's great news.

**Comment by genio** [comment]
@adamkennedy Were you able to get the SSH keys sorted with Matt so we could push changes to the site?

**Pull request merged**
