### PR TITLE
Add release notes for 64-bit 5.38.2.1, 5.38.2.2 and 5.36.3.1 

### PR DESCRIPTION
**Pull request by shawnlaffan**
MSI and zip files are at https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_53821_64bit

If those all look good then I'll set that release as latest.

@genio - are you able to update the releases.json file and the release table (if it is not automatically generated)?

### CODE REVIEW

**Comment by shawnlaffan** [comment]
5.36.3.1 files are at https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_53631_64bit

~And now I see the relevant commit message has the wrong number.  It's associated with a tag now so is perhaps best left as-is.~ Edit - Was thinking of wrong repo.  Will update.

**Comment by shawnlaffan** [comment]
5.38.2.2 files are at https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_53822_64bit

**Comment by shawnlaffan** [comment]
@genio - ping

**Comment by genio** [comment]
The release notes have been added to the site. I'll need to take some time to add them to the tables and JSON by hand. There's a script in there to build them, but I haven't vetted it yet and we no longer ship the 32-bit versions, so things are a tad different from what they used to be

**Comment by shawnlaffan** [comment]
Thanks.  
Ideally we will build the json file as a step in the build process.  The relevant issue is https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/163

**Pull request merged**
