### PR TITLE
Add new releases.

### PR DESCRIPTION
**Pull request by genio**
Add the new release to the main page.
Add the new releases to the releases page.
Add the new releases to the JSON releases file.

### CODE REVIEW

**Comment by genio** [comment]
This should complete the work for [issue #163](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/163)

**Comment by shawnlaffan** [comment]
There's a lot of HTML in there but it seems to be good.  

Does it obviate https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/163 or does it address one of the other issues?  e.g. #47

**Comment by genio** [comment]
Yeah, stupid VSCode did stupid things. Sorry about that.

**Comment by genio** [comment]
I'll go ahead and publish this out and we can fix whatever I screwed up after the fact.

**Pull request merged**
